# Generate the $16$ point Walsh matrix
> using scipy

`hadamard(n, dtype=<class 'int'>)`
- `n` is the order of the matrix (must be power of 2) 

In [44]:
import numpy as np
from scipy.linalg import hadamard
V = hadamard(16)
print(V)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1  1 -1]
 [ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1]
 [ 1  1 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1  1  1]
 [ 1 -1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1  1 -1]
 [ 1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1 -1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1 -1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1]]


Get the required row values:

row: 1, 4, 10

In [45]:
W1 = V[0]
W4 = V[3]
W10 = V[9]

print(f"W1: {W1}\n")
print(f"W4: {W4}\n")
print(f"W10: {W10}\n")

W1: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

W4: [ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1]

W10: [ 1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1]



# Modulate

> Check `ADSP_Write7.pdf` p.520 for more info.

### Step (1): Change $0$ to $-1$.
### Step (2): Modulate

Modulate `[1 0 1]` by `W1`

In [46]:
W1_101 = np.concatenate([W1, -W1, W1])

print(W1_101)

[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]


Modulate `[1 1 0]` by `W4`

In [47]:
W4_110 = np.concatenate([W4, W4, -W4])

print(W4_110)

[ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1
  1 -1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1]


Modulate `[0 1 1]` by `W10`

In [48]:
W10_011 = np.concatenate([-W10, W10, W10])

print(W10_011)

[-1  1 -1  1 -1  1 -1  1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1
 -1  1 -1  1 -1  1 -1  1  1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1]


### Step (3): 相合

In [49]:
x = W1_101 + W4_110 + W10_011
print(f"Step 3 result (answer of  7 (a)):\n {x}\n")

Step 3 result (answer of  7 (a)):
 [ 1  1 -1  3  1  1 -1  3  3 -1  1  1  3 -1  1  1  1 -3 -1 -1  1 -3 -1 -1
 -1 -1 -3  1 -1 -1 -3  1  1  1  3 -1  1  1  3 -1 -1  3  1  1 -1  3  1  1]



# Demodulation

> Check `ADSP_Write7.pdf` p.521 for more info.

In [50]:
x1 = np.split(x, 3)[0]
x2 = np.split(x, 3)[1]
x3 = np.split(x, 3)[2]

print(f"x1: {x1}\n")
print(f"x2: {x2}\n")
print(f"x3: {x3}\n")

x1: [ 1  1 -1  3  1  1 -1  3  3 -1  1  1  3 -1  1  1]

x2: [ 1 -3 -1 -1  1 -3 -1 -1 -1 -1 -3  1 -1 -1 -3  1]

x3: [ 1  1  3 -1  1  1  3 -1 -1  3  1  1 -1  3  1  1]



In [54]:
orig_data_1 = [1, 0, 1]
orig_data_2 = [1, 1, 0]
orig_data_3 = [0, 1, 1]

recover_data_1 = []
res = np.inner(x1, W1) / 16
if res > 0:
    recover_data_1.append(1)
else:
    recover_data_1.append(0)

res = np.inner(x2, W1) / 16
if res > 0:
    recover_data_1.append(1)
else:
    recover_data_1.append(0)

res = np.inner(x3, W1) / 16
if res > 0:
    recover_data_1.append(1)
else:
    recover_data_1.append(0)

print(f"recover_data_1: {recover_data_1}\n")
print(f"equivalent to orig_data_1?: {recover_data_1 == orig_data_1}\n")

recover_data_2 = []
res = np.inner(x1, W4) / 16
if res > 0:
    recover_data_2.append(1)
else:
    recover_data_2.append(0)

res = np.inner(x2, W4) / 16
if res > 0:
    recover_data_2.append(1)
else:
    recover_data_2.append(0)
res = np.inner(x3, W4) / 16
if res > 0:
    recover_data_2.append(1)
else:
    recover_data_2.append(0)

print(f"recover_data_2: {recover_data_2}\n")
print(f"equivalent to orig_data_2?: {recover_data_2 == orig_data_2}\n")

recover_data_3 = []
res = np.inner(x1, W10) / 16
if res > 0:
    recover_data_3.append(1)
else:
    recover_data_3.append(0)

res = np.inner(x2, W10) / 16
if res > 0:
    recover_data_3.append(1)
else:
    recover_data_3.append(0)

res = np.inner(x3, W10) / 16
if res > 0:
    recover_data_3.append(1)
else:
    recover_data_3.append(0)

print(f"recover_data_3: {recover_data_3}\n")
print(f"equivalent to orig_data_3?: {recover_data_3 == orig_data_3}\n")

recover_data_1: [1, 0, 1]

equivalent to orig_data_1?: True

recover_data_2: [1, 1, 0]

equivalent to orig_data_2?: True

recover_data_3: [0, 1, 1]

equivalent to orig_data_3?: True

